function nY(){}
function oW(a,b){a.Sb(b)}
function $X(a,b){jM.call(this,a,b)}
function GW(a,b){return new $X(a,b)}
function kY(){this.a=pY(new qY)}
function qY(){this.a=dj($doc);this.b=new wy(this.a)}
function rY(a){var b;b=new UQ;ti(b.a,Y0);TQ(b,oy(a));ti(b.a,Z0);return new _x(wi(b.a))}
function CW(a){var b;!a.j&&(a.j=(b=GW((!a.a&&(a.a=new Hm),a.a),(!a.k&&(a.k=new kY(new nY)),a.k),!a.i&&(a.i=new dY)),oW(b,(!a.d&&(a.d=new QL),a.d)),b));return a.j}
function pY(a){var b,c,d,e,f,g,h,i,j,k,l,m;c=new BF(rY(a.a).a);c.q.style[P0]=Q0;c.q.style[R0]=Q0;b=yy(c.q);vy(a.b);b.b?Ei(b.b,b.a,b.c):Ay(b.a);zF(c,(d=new oF,mF(d,1),nF(d,3),gF(d,0,0,(e=new uF,e.q[S0]='tituloHome',vE(e.a,'BIENVENIDO',false),e.q.style[P0]='36px',e.q.style[R0]=Q0,e)),gF(d,1,0,(f=new oF,mF(f,1),nF(f,6),gF(f,0,0,(h=new uF,h.q[S0]=T0,vE(h.a,'\xBFQue es EventosUNI?',false),h)),gF(f,1,0,(i=new uF,i.q[S0]=U0,vE(i.a,V0,false),i)),gF(f,2,0,(j=new uF,j.q[S0]=T0,vE(j.a,'\xBFA quien esta dirigido?',false),j)),gF(f,3,0,(k=new uF,k.q[S0]=U0,vE(k.a,V0,false),k)),gF(f,4,0,(l=new uF,l.q[S0]=T0,vE(l.a,'\xBFPor que usar EventosUNI?',false),l)),gF(f,5,0,(m=new uF,m.q[S0]=U0,vE(m.a,V0,false),m)),f.q[S0]='cuadroBienvenida',f.q.style[P0]=Q0,f.q.style[R0]=Q0,f.f[W0]=2,f)),gF(d,2,0,(g=new OJ,g.q.style[P0]='15px',g.q.style[R0]=Q0,g)),d.q[S0]=X0,d.q.style[P0]=Q0,d.q.style[R0]=Q0,d.f[W0]=3,d),vy(a.b));return c}
var V0='Descripcion...',U0='textBienvenido',T0='textsubBienvenido';dx(505,1,D_);_.eb=function dX(){mN(this.b,CW(this.a.a))};dx(523,407,t_,$X);_.Tb=function _X(){};_.Ub=function aY(){};_.Xb=function bY(){eM(this,new bP((WY(),UY),this))};dx(526,411,{},kY);_.Zb=function lY(){return this.a};_.a=null;dx(527,1,{},nY);dx(528,1,{},qY);_.a=null;_.b=null;var Nv=LP(I0,'HomePresenter',523),Qv=LP(I0,'HomeView',526),Pv=LP(I0,'HomeView_BinderImpl',527),Ov=LP(I0,'HomeView_BinderImpl$Widgets',528);G_(ah)(1);