function iY(){}
function jW(a,b){a.Sb(b)}
function VX(a,b){eM.call(this,a,b)}
function BW(a,b){return new VX(a,b)}
function fY(){this.a=kY(new lY)}
function lY(){this.a=fj($doc);this.b=new yy(this.a)}
function mY(a){var b;b=new PQ;ti(b.a,U0);OQ(b,qy(a));ti(b.a,V0);return new by(wi(b.a))}
function xW(a){var b;!a.j&&(a.j=(b=BW((!a.a&&(a.a=new Jm),a.a),(!a.k&&(a.k=new fY(new iY)),a.k),!a.i&&(a.i=new $X)),jW(b,(!a.d&&(a.d=new LL),a.d)),b));return a.j}
function kY(a){var b,c,d,e,f,g,h,i,j,k,l,m;c=new wF(mY(a.a).a);c.q.style[L0]=M0;c.q.style[N0]=M0;b=Ay(c.q);xy(a.b);b.b?Ei(b.b,b.a,b.c):Cy(b.a);uF(c,(d=new jF,hF(d,1),iF(d,3),bF(d,0,0,(e=new pF,e.q[O0]='tituloHome',qE(e.a,'BIENVENIDO',false),e.q.style[L0]='36px',e.q.style[N0]=M0,e)),bF(d,1,0,(f=new jF,hF(f,1),iF(f,6),bF(f,0,0,(h=new pF,h.q[O0]=P0,qE(h.a,'\xBFQue es EventosUNI?',false),h)),bF(f,1,0,(i=new pF,i.q[O0]=Q0,qE(i.a,R0,false),i)),bF(f,2,0,(j=new pF,j.q[O0]=P0,qE(j.a,'\xBFA quien esta dirigido?',false),j)),bF(f,3,0,(k=new pF,k.q[O0]=Q0,qE(k.a,R0,false),k)),bF(f,4,0,(l=new pF,l.q[O0]=P0,qE(l.a,'\xBFPor que usar EventosUNI?',false),l)),bF(f,5,0,(m=new pF,m.q[O0]=Q0,qE(m.a,R0,false),m)),f.q[O0]='cuadroBienvenida',f.q.style[L0]=M0,f.q.style[N0]=M0,f.f[S0]=2,f)),bF(d,2,0,(g=new JJ,g.q.style[L0]='15px',g.q.style[N0]=M0,g)),d.q[O0]=T0,d.q.style[L0]=M0,d.q.style[N0]=M0,d.f[S0]=3,d),xy(a.b));return c}
var R0='Descripcion...',Q0='textBienvenido',P0='textsubBienvenido';fx(502,1,y_);_.eb=function $W(){hN(this.b,xW(this.a.a))};fx(520,404,o_,VX);_.Tb=function WX(){};_.Ub=function XX(){};_.Xb=function YX(){_L(this,new YO((RY(),PY),this))};fx(523,408,{},fY);_.Zb=function gY(){return this.a};_.a=null;fx(524,1,{},iY);fx(525,1,{},lY);_.a=null;_.b=null;var Pv=GP(E0,'HomePresenter',520),Sv=GP(E0,'HomeView',523),Rv=GP(E0,'HomeView_BinderImpl',524),Qv=GP(E0,'HomeView_BinderImpl$Widgets',525);B_(ah)(1);