function SX(){}
function TV(a,b){a.Sb(b)}
function DX(a,b){OL.call(this,a,b)}
function jW(a,b){return new DX(a,b)}
function PX(){this.b=UX(new VX)}
function VX(){this.b=Zi($doc);this.c=new hy(this.b)}
function WX(a){var b;b=new xQ;b.b.b+=z0;wQ(b,_x(a));b.b.b+=A0;return new Mx(b.b.b)}
function fW(a){var b;!a.k&&(a.k=(b=jW((!a.b&&(a.b=new Bm),a.b),(!a.n&&(a.n=new PX(new SX)),a.n),!a.j&&(a.j=new IX)),TV(b,(!a.e&&(a.e=new tL),a.e)),b));return a.k}
function UX(a){var b,c,d,e,f,g,h,i,j,k,l,m;c=new gF(WX(a.b).b);c.r.style[q0]=r0;c.r.style[s0]=r0;b=jy(c.r);gy(a.c);b.c?Di(b.c,b.b,b.d):ly(b.b);eF(c,(d=new VE,TE(d,1),UE(d,3),NE(d,0,0,(e=new _E,e.r[t0]='tituloHome',aE(e.b,'BIENVENIDO',false),e.r.style[q0]='36px',e.r.style[s0]=r0,e)),NE(d,1,0,(f=new VE,TE(f,1),UE(f,6),NE(f,0,0,(h=new _E,h.r[t0]=u0,aE(h.b,'\xBFQue es EventosUNI?',false),h)),NE(f,1,0,(i=new _E,i.r[t0]=v0,aE(i.b,w0,false),i)),NE(f,2,0,(j=new _E,j.r[t0]=u0,aE(j.b,'\xBFA quien esta dirigido?',false),j)),NE(f,3,0,(k=new _E,k.r[t0]=v0,aE(k.b,w0,false),k)),NE(f,4,0,(l=new _E,l.r[t0]=u0,aE(l.b,'\xBFPor que usar EventosUNI?',false),l)),NE(f,5,0,(m=new _E,m.r[t0]=v0,aE(m.b,w0,false),m)),f.r[t0]='cuadroBienvenida',f.r.style[q0]=r0,f.r.style[s0]=r0,f.g[x0]=2,f)),NE(d,2,0,(g=new sJ,g.r.style[q0]='15px',g.r.style[s0]=r0,g)),d.r[t0]=y0,d.r.style[q0]=r0,d.r.style[s0]=r0,d.g[x0]=3,d),gy(a.c));return c}
var w0='Descripcion...',v0='textBienvenido',u0='textsubBienvenido';Vw(498,1,g_);_.fb=function IW(){RM(this.c,fW(this.b.b))};Vw(516,400,Y$,DX);_.Tb=function EX(){};_.Ub=function FX(){};_.Xb=function GX(){JL(this,new GO((zY(),xY),this))};Vw(519,404,{},PX);_.Zb=function QX(){return this.b};_.b=null;Vw(520,1,{},SX);Vw(521,1,{},VX);_.b=null;_.c=null;var Dv=oP(j0,'HomePresenter',516),Gv=oP(j0,'HomeView',519),Fv=oP(j0,'HomeView_BinderImpl',520),Ev=oP(j0,'HomeView_BinderImpl$Widgets',521);j_(ah)(1);