function Fhb(){}
function ofb(a,b){a.Zc(b)}
function qhb(a,b){n3.call(this,a,b)}
function Jfb(a,b){return new qhb(a,b)}
function Chb(){this.a=Hhb(new Ihb)}
function Ihb(){this.a=Fj($doc);this.b=new cJ(this.a)}
function Jhb(a){var b;b=new G8;Hi(b.a,Qub);A8(b,CI(a));Hi(b.a,Sub);return new nI(Mi(b.a))}
function Efb(a){var b;!a.j&&(a.j=(b=Jfb((!a.a&&(a.a=new Fo),a.a),(!a.k&&(a.k=new Chb(new Fhb)),a.k),!a.i&&(a.i=new vhb)),ofb(b,(!a.d&&(a.d=new S2),a.d)),b));return a.j}
function Hhb(a){var b,c,d,e,f,g,i,j,k,n,o;c=new RT(Jhb(a.a).a);c.z[jvb]=arb;c.z.style[kvb]=lvb;c.z.style[Mub]=lvb;b=eJ(c.z);bJ(a.b);b.b?Ui(b.b,b.a,b.c):gJ(b.a);PT(c,(d=new wT,uT(d,1),vT(d,2),CS(d,0,0,(e=new JT,UQ(e.b,mvb,false),GT(e),e.z.style[kvb]=nvb,e.z.style[Mub]=lvb,e)),CS(d,1,0,(f=new wT,uT(f,1),vT(f,6),CS(f,0,0,(g=new JT,UQ(g.b,ovb,false),GT(g),g)),CS(f,1,0,(i=new JT,UQ(i.b,pvb,false),GT(i),i)),CS(f,2,0,(j=new JT,UQ(j.b,qvb,false),GT(j),j)),CS(f,3,0,(k=new JT,UQ(k.b,pvb,false),GT(k),k)),CS(f,4,0,(n=new JT,UQ(n.b,rvb,false),GT(n),n)),CS(f,5,0,(o=new JT,UQ(o.b,pvb,false),GT(o),o)),f.z.style[kvb]=lvb,f.z.style[Mub]=lvb,f.n[xub]=2,f)),d.z.style[kvb]=lvb,d.z.style[Mub]=lvb,d.n[xub]=3,d),bJ(a.b));return c}
var nvb='36px',mvb='BIENVENIDO',pvb='Descripcion...',svb='HomePresenter',tvb='HomeView',uvb='HomeView_BinderImpl',vvb='HomeView_BinderImpl$Widgets',qvb='\xBFA quien esta dirigido?',rvb='\xBFPor que usar EventosUNI?',ovb='\xBFQue es EventosUNI?';VG(672,1,qob);_.hb=function tgb(){r4(this.b,Efb(this.a.a))};VG(692,549,gob,qhb);_.$c=function rhb(){};_.ad=function shb(){};_.cd=function thb(){h3(this,new j6((Qhb(),Ohb),this))};VG(695,553,{},Chb);_.gd=function Dhb(){return this.a};_.a=null;VG(696,1,{},Fhb);VG(697,1,{},Ihb);_.a=null;_.b=null;var HD=Y6(Isb,svb,692),KD=Y6(Isb,tvb,695),JD=Y6(Isb,uvb,696),ID=Y6(Isb,vvb,697);vob(mh)(2);